group: multiblimp
task:
- multiblimp_krl
- multiblimp_vep
- multiblimp_olo
- multiblimp_swe
- multiblimp_hit
- multiblimp_bel
- multiblimp_hbs
- multiblimp_tur
- multiblimp_ukr
- multiblimp_bua
- multiblimp_mkd
- multiblimp_hin
- multiblimp_est
- multiblimp_spa
- multiblimp_hbo
- multiblimp_pcm
- multiblimp_lij
- multiblimp_ron
- multiblimp_orv
- multiblimp_lav
- multiblimp_ota
- multiblimp_eus
- multiblimp_hun
- multiblimp_gle
- multiblimp_ita
- multiblimp_kxh
- multiblimp_isl
- multiblimp_hyw
- multiblimp_por
- multiblimp_hsb
- multiblimp_eng
- multiblimp_bre
- multiblimp_egy
- multiblimp_yrl
- multiblimp_quc
- multiblimp_grc
- multiblimp_bho
- multiblimp_ell
- multiblimp_fro
- multiblimp_urd
- multiblimp_koi
- multiblimp_bor
- multiblimp_wbp
- multiblimp_frm
- multiblimp_sah
- multiblimp_guj
- multiblimp_nld
- multiblimp_slk
- multiblimp_urb
- multiblimp_kaz
- multiblimp_mar
- multiblimp_ces
- multiblimp_rus
- multiblimp_chu
- multiblimp_hye
- multiblimp_got
- multiblimp_ben
- multiblimp_abk
- multiblimp_nds
- multiblimp_bul
- multiblimp_fin
- multiblimp_slv
- multiblimp_mdf
- multiblimp_tpn
- multiblimp_nhi
- multiblimp_apu
- multiblimp_wol
- multiblimp_ttc
- multiblimp_cym
- multiblimp_cat
- multiblimp_fao
- multiblimp_kat
- multiblimp_san
- multiblimp_arb
- multiblimp_uig
- multiblimp_deu
- multiblimp_sqi
- multiblimp_fra
- multiblimp_uzb
- multiblimp_myv
- multiblimp_dan
- multiblimp_tam
- multiblimp_amh
- multiblimp_pol
- multiblimp_lat
- multiblimp_aln
- multiblimp_kir
- multiblimp_kmr
- multiblimp_fas
- multiblimp_xnr
- multiblimp_lit
- multiblimp_glg
- multiblimp_gla
- multiblimp_aqz
- multiblimp_azz
- multiblimp_sms
- multiblimp_kpv
- multiblimp_sme
- multiblimp_xcl
- multiblimp_heb
- multiblimp_xpg
aggregate_metric_list:
- metric: acc
  aggregation: mean
  weight_by_size: true
metadata:
  version: 1.0
